name: Deploy install.sh to silly.static

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.SILLY_ENTERPRISES_BOT_APP_ID }}
          private_key: ${{ secrets.SILLY_ENTERPRISES_BOT_2025_04_05_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Clone static.silly.enterprises
        run: |
          git clone https://github.com/silly-enterprises/static.silly.enterprises
          mkdir -p static.silly.enterprises/scripts
          cp install.sh static.silly.enterprises/scripts/install.sh
          cp install.ps1 static.silly.enterprises/scripts/install.ps1
          cd static.silly.enterprises
          git config user.name "silly enterprises bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scripts/install.sh
          git add scripts/install.ps1
          git commit -m "Update from silly.install"
          git push https://x-access-token:${{ steps.create_token.outputs.token }}@github.com/silly-enterprises/static.silly.enterprises.git HEAD:main