name: Deploy install.sh to silly.static

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone static.silly.enterprises
        run: |
          git clone https://github.com/silly-enterprises/static.silly.enterprises
          cd static.silly.enterprises
          mkdir -p docs
          cp install.sh static.silly.enterprises/docs/install.sh
          cp install.ps1 static.silly.enterprises/docs/install.ps1
          cd static.silly.enterprises
          git config user.name "silly-bot[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/install.sh
          git commit -m "Update install.sh from silly.install"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/silly-enterprises/static.silly.enterprises.git HEAD:main